# Generated by Django 3.2 on 2022-05-09 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='tweet')),
                ('tweet_img', models.ImageField(blank=True, null=True, upload_to='images/tweet', verbose_name='tweet image')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='tweet date')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='tweet edit')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('user_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tweet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='comment')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='images/comment', verbose_name='comment image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_tweet', to='api.tweet')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
