# Generated by Django 4.0 on 2023-05-17 11:59

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='tweet')),
                ('tweet_img', models.ImageField(blank=True, null=True, upload_to=api.models.return_tweet_image_path, verbose_name='tweet image')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='tweet date')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='tweet edit at')),
                ('tweet_like', models.ManyToManyField(blank=True, related_name='tweet_like', to=settings.AUTH_USER_MODEL)),
                ('user_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tweet', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='comment')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to=api.models.return_comment_image_path, verbose_name='comment image')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='comment edit at')),
                ('comment_like', models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_tweet', to='api.tweet')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='accounts.user')),
            ],
        ),
    ]
