# Generated by Django 3.2 on 2022-05-14 19:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.return_comment_image_path, verbose_name='comment image'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.return_tweet_image_path, verbose_name='tweet image'),
        ),
    ]
