# Generated by Django 4.0 on 2023-05-17 11:59

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active account')),
                ('is_admin', models.BooleanField(default=False, verbose_name='super account')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff user')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='joined services')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date')),
                ('account', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='unique account id')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='bio')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=accounts.models.return_icon_path, verbose_name='usericon')),
                ('link', models.URLField(blank=True, max_length=1000, verbose_name='url')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.user')),
            ],
        ),
    ]
