# Generated by Django 3.2 on 2022-04-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='unique account id'),
        ),
    ]
