# Generated by Django 3.2 on 2022-05-14 19:23

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date')),
                ('account', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='unique account id')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='bio')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=accounts.models.return_icon_path, verbose_name='usericon')),
                ('link', models.URLField(blank=True, max_length=1000, verbose_name='url')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
